### ISSUE TITLE
Error running nom install

### ISSUE THREAD

**Issue by Stiggler** [asimhsidd/MMM-VideoPlayer#1]
Hi,

I get an error running 'npm install# for MMM-Video Player.
Here is the content of 'npm-debug.log':

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'https://github.com/asimhsidd/MMM-VideoPlayer.git' ]
2 info using npm@3.10.10
3 info using node@v6.14.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData https://github.com/asimhsidd/MMM-VideoPlayer.git
8 silly fetchOtherPackageData https://github.com/asimhsidd/MMM-VideoPlayer.git
9 silly cache add args [ 'https://github.com/asimhsidd/MMM-VideoPlayer.git', null ]
10 verbose cache add spec https://github.com/asimhsidd/MMM-VideoPlayer.git
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'https://github.com/asimhsidd/MMM-VideoPlayer.git',
11 silly cache add   scope: null,
11 silly cache add   escapedName: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: 'https://github.com/asimhsidd/MMM-VideoPlayer.git',
11 silly cache add   spec: 'git+https://github.com/asimhsidd/MMM-VideoPlayer.git',
11 silly cache add   type: 'hosted',
11 silly cache add   hosted:
11 silly cache add    { type: 'github',
11 silly cache add      ssh: 'git@github.com:asimhsidd/MMM-VideoPlayer.git',
11 silly cache add      sshUrl: 'git+ssh://git@github.com/asimhsidd/MMM-VideoPlayer.git',
11 silly cache add      httpsUrl: 'git+https://github.com/asimhsidd/MMM-VideoPlayer.git',
11 silly cache add      gitUrl: 'git://github.com/asimhsidd/MMM-VideoPlayer.git',
11 silly cache add      shortcut: 'github:asimhsidd/MMM-VideoPlayer',
11 silly cache add      directUrl: 'https://raw.githubusercontent.com/asimhsidd/MMM-VideoPlayer/master/package.json' } }
12 verbose addRemoteGit caching https://github.com/asimhsidd/MMM-VideoPlayer.git
13 verbose addRemoteGit git+https://github.com/asimhsidd/MMM-VideoPlayer.git is a repository hosted by github
14 silly tryClone cloning git+https://github.com/asimhsidd/MMM-VideoPlayer.git via git+https://github.com/asimhsidd/MMM-VideoPlayer.git
15 verbose tryClone git-https-github-com-asimhsidd-MMM-VideoPlayer-git-1e8ecaf1 not in flight; caching
16 verbose correctMkdir /home/pi/.npm/_git-remotes correctMkdir not in flight; initializing
17 info git [ 'clone',
17 info git   '--template=/home/pi/.npm/_git-remotes/_templates',
17 info git   '--mirror',
17 info git   'https://github.com/asimhsidd/MMM-VideoPlayer.git',
17 info git   '/home/pi/.npm/_git-remotes/git-https-github-com-asimhsidd-MMM-VideoPlayer-git-1e8ecaf1' ]
18 verbose mirrorRemote git+https://github.com/asimhsidd/MMM-VideoPlayer.git git clone https://github.com/asimhsidd/MMM-VideoPlayer.git
19 verbose correctMkdir /home/pi/.npm/_git-remotes correctMkdir not in flight; initializing
20 verbose setPermissions git+https://github.com/asimhsidd/MMM-VideoPlayer.git set permissions on /home/pi/.npm/_git-remotes/git-https-github-com-asimhsidd-MMM-VideoPlayer-git-1e8ecaf1
21 verbose resolveHead git+https://github.com/asimhsidd/MMM-VideoPlayer.git original treeish: master
22 info git [ 'rev-list', '-n1', 'master' ]
23 silly resolveHead git+https://github.com/asimhsidd/MMM-VideoPlayer.git resolved treeish: 4804ba3453b9c0381ebf41ca567417fab0620f46
24 verbose resolveHead git+https://github.com/asimhsidd/MMM-VideoPlayer.git resolved Git URL: git+https://github.com/asimhsidd/MMM-VideoPlayer.git#4804ba3453b9c0381ebf41ca567417fab0620f46
25 silly resolveHead Git working directory: /tmp/npm-26104-702d2574/git-cache-3017a051/4804ba3453b9c0381ebf41ca567417fab0620f46
26 info git [ 'clone',
26 info git   '/home/pi/.npm/_git-remotes/git-https-github-com-asimhsidd-MMM-VideoPlayer-git-1e8ecaf1',
26 info git   '/tmp/npm-26104-702d2574/git-cache-3017a051/4804ba3453b9c0381ebf41ca567417fab0620f46' ]
27 verbose cloneResolved git+https://github.com/asimhsidd/MMM-VideoPlayer.git clone Klone nach '/tmp/npm-26104-702d2574/git-cache-3017a051/4804ba3453b9c0381ebf41ca567417fab0620f46'...
27 verbose cloneResolved Fertig.
28 info git [ 'checkout', '4804ba3453b9c0381ebf41ca567417fab0620f46' ]
29 verbose checkoutTreeish git+https://github.com/asimhsidd/MMM-VideoPlayer.git checkout Note: checking out '4804ba3453b9c0381ebf41ca567417fab0620f46'.
29 verbose checkoutTreeish
29 verbose checkoutTreeish You are in 'detached HEAD' state. You can look around, make experimental
29 verbose checkoutTreeish changes and commit them, and you can discard any commits you make in this
29 verbose checkoutTreeish state without impacting any branches by performing another checkout.
29 verbose checkoutTreeish
29 verbose checkoutTreeish If you want to create a new branch to retain commits you create, you may
29 verbose checkoutTreeish do so (now or later) by using -b with the checkout command again. Example:
29 verbose checkoutTreeish
29 verbose checkoutTreeish   git checkout -b new_branch_name
29 verbose checkoutTreeish
29 verbose checkoutTreeish HEAD ist jetzt bei 4804ba3... Update index.html
30 info git [ 'submodule', '-q', 'update', '--init', '--recursive' ]
31 verbose updateSubmodules git+https://github.com/asimhsidd/MMM-VideoPlayer.git submodule update
32 verbose addLocalDirectory /home/pi/.npm/MMM-VideoPlayer/1.0.0/package.tgz not in flight; packing
33 verbose correctMkdir /home/pi/.npm correctMkdir not in flight; initializing
34 verbose tar pack [ '/home/pi/.npm/MMM-VideoPlayer/1.0.0/package.tgz',
``

I am a newbie and would be very thankful for help

**Comment by asimhsidd** [comment]
Thanks for identifying the issue. I changed the package.json. Give it a try now. Please give your feedback.

**Comment by Stiggler** [comment]
Okay, I will try it this evening! 
Thanks!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asimhsidd** [comment]
Update please so I can close this issue.

**Comment by Stiggler** [comment]
Npm Install worked!

Thanks!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
